name: check

on:
  workflow_dispatch:
    inputs:
      python-version:
        type: string
        default: '3.10'
        description: 'Python version to use'
  schedule:
    - cron: '0 6 * * *' # 每天 6 点执行
  push:
    branches:
      - main
    paths:
      - .signer/**/*.json

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["${{ github.event.inputs.python-version || '3.10' }}"]

    env:
      TZ: Asia/Shanghai # 设置为东八区时间

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Cache Python dependencies
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-pip-deps-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ matrix.python-version }}-pip-deps-

      # 3. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

  install:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      # 4. Upgrade pip
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      # 5. Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --no-cache-dir -U tg-signer TgCrypto
        env:
          PIP_CACHE_DIR: ~/.cache/pip

      # 6. Verify tg-signer installation (and debug installation paths)
      - name: Verify tg-signer installation
        run: |
          set -e
          echo "Python executable: $(which python)"
          echo "Pip executable: $(which pip)"
          pip show tg-signer || echo "tg-signer was not installed!"
          echo "Python user base: $(python -m site --user-base)"
          echo "Contents of bin folder: $(ls $(python -m site --user-base)/bin || echo 'Bin folder is empty')"

      # 7. Cache node modules
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # 8. Install Node.js dependencies
      - name: Install ai-markdown-translator globally
        run: npm install -g ai-markdown-translator@1.0.15

  check-tg-signer:
    runs-on: ubuntu-latest
    needs: install

    steps:
      # 9. Ensure PATH includes ~/.local/bin
      - name: Ensure PATH for tg-signer
        run: |
          export PATH="$PATH:$(python -m site --user-base)/bin"
          echo "PATH is now: $PATH"

      # 10. Validate tg-signer commands
      - name: Validate tg-signer
        run: |
          set -e
          tg-signer --help || echo "Unable to run tg-signer help"

      # 11. Run tg-signer
      - name: Run tg-signer
        run: |
          export PATH="$PATH:$(python -m site --user-base)/bin"
          rm -rf ./tg-signer.log
          tg-signer run-once

  process-logs:
    runs-on: ubuntu-latest
    needs: check-tg-signer

    steps:
      # 12. Rename log to md and copy
      - name: Rename log to md
        run: |
          log_path="./$(date +%Y/%m/%d).md"
          mkdir -p $(dirname "$log_path")
          mv ./tg-signer.log "$log_path"
          cp "$log_path" ./log.md

  setup-node:
    runs-on: ubuntu-latest
    needs: process-logs

    steps:
      # 13. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

  translate-log:
    runs-on: ubuntu-latest
    needs: setup-node

    steps:
      # 14. Translate log to Chinese markdown
      - name: Translate log to Chinese
        run: ai-markdown-translator -i log.md -l "中文，并重新整理为markdown格式（要求整理标题和内容，要很好的区分每个对应的任务和内容）"

  commit-and-push:
    runs-on: ubuntu-latest
    needs: translate-log

    steps:
      # 15. Commit and push changes
      - name: Commit and push changes
        run: |
          git config --local user.email "action@h7ml.cn"
          git config --local user.name "GitHub Action"
          git config advice.ignoredHook false
          git add ./$(date +%Y/%m/%d).md ./log.md
          git add .signer
          git commit -m "check $(date +%Y/%m/%d)" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
