name: check

on:
  workflow_dispatch:
    inputs:
      python-version:
        type: string
        default: '3.10'
        description: 'Python version to use'
  schedule:
    - cron: '0 6 * * *'
  push:
    branches:
      - main
    paths:
      - .signer/**/*.json

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["${{ github.event.inputs.python-version || '3.10' }}"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -U tg-signer TgCrypto

      - name: Check tg-signer install path
        run: |
          which tg-signer
          echo "tg-signer path is: $(which tg-signer)"

      - name: Show pip freeze
        run: |
          pip freeze

      - name: generate signer sign log
        run: |
          year=$(date +%Y)
          month=$(date +%m)
          day=$(date +%d)
          rm -f "$year/$month/$day/sign.log"  # 删除旧日志
          mkdir -p "$year/$month/$day"
          touch "$year/$month/$day/sign.log"
          echo "# Signer Log - $(date '+%Y-%m-%d')" > "$year/$month/$day/sign.log"
          echo "## Environment" >> "$year/$month/$day/sign.log"
          echo "\`\`\`" >> "$year/$month/$day/sign.log"
          python --version >> "$year/$month/$day/sign.log"
          pip freeze >> "$year/$month/$day/sign.log"
          echo "\`\`\`" >> "$year/$month/$day/sign.log"

      - name: Run tg-signer
        run: |
          set -e
          $(which tg-signer) run-once | tee "$(date +%Y-%m-%d).md"

      - name: commit
        run: |
          git config --local user.email "action@h7ml.cn"
          git config --local user.name "GitHub Action"
          git config advice.ignoredHook false
          git diff --quiet || git add .
          git commit -m "check $(date +%Y/%m/%d)" || echo "No changes to commit"
          git push origin main
