name: check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -U tg-signer

      - name: Check tg-signer install path
        run: |
          which tg-signer
          echo "tg-signer path is: $(which tg-signer)"

      - name: Show pip freeze
        run: |
          pip freeze

      - name: Run tg-signer
        run: |
          set -e
          $(which tg-signer) path run-once
