name: check

on:
  workflow_dispatch:
    inputs:
      python-version:
        type: string
        default: '3.10'
        description: 'Python version to use'
  schedule:
    - cron: '0 6 * * *' # 每天6点执行
  push:
    branches:
      - main
    paths:
      - .signer/**/*.json

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["${{ github.event.inputs.python-version || '3.10' }}"]

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-deps-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ matrix.python-version }}-deps-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

  install:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install tg-signer and dependencies
        run: |
          python -m pip install --no-cache-dir -U tg-signer TgCrypto
        env:
          PIP_CACHE_DIR: ~/.cache/pip

      - name: Verify tg-signer installation
        run: |
          set -e
          echo "Python executable: $(which python)"
          echo "Pip executable: $(which pip)"
          pip show tg-signer || { echo "tg-signer is NOT installed!"; exit 1; }
          tg_signer_bin="$(python -m site --user-base)/bin/tg-signer"
          if [ ! -f "$tg_signer_bin" ]; then
            echo "tg-signer binary file was not found at $tg_signer_bin"
            exit 1
          fi
          echo "tg-signer is correctly installed at: $tg_signer_bin"

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install ai-markdown-translator
        run: npm install -g ai-markdown-translator@1.0.15

  check-tg-signer:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Run tg-signer
        run: |
          set -e
          tg_signer_bin="$(python -m site --user-base)/bin/tg-signer"
          if [ ! -f "$tg_signer_bin" ]; then
            echo "ERROR: tg-signer binary file not found at $tg_signer_bin"
            exit 1
          fi
          rm -rf ./tg-signer.log
          $tg_signer_bin run-once

  process-logs:
    runs-on: ubuntu-latest
    needs: check-tg-signer

    steps:
      - name: Rename log file
        run: |
          log_path="./$(date +%Y/%m/%d).md"
          mkdir -p $(dirname "$log_path")
          mv ./tg-signer.log "$log_path"
          cp "$log_path" ./log.md

  setup-node:
    runs-on: ubuntu-latest
    needs: process-logs

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

  translate-log:
    runs-on: ubuntu-latest
    needs: setup-node

    steps:
      - name: Translate log
        run: ai-markdown-translator -i log.md -l "中文，并重新整理为markdown格式（要求整理标题和内容，要很好的区分每个对应的任务和内容）"

  commit-and-push:
    runs-on: ubuntu-latest
    needs: translate-log

    steps:
      - name: Commit and push changes
        run: |
          git config --local user.email "action@h7ml.cn"
          git config --local user.name "GitHub Action"
          git add ./$(date +%Y/%m/%d).md ./log.md
          git commit -m "check $(date +%Y/%m/%d)" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
