name: check

on:
  workflow_dispatch:
    inputs:
      python-version:
        type: string
        default: '3.10'
        description: 'Python version to use'
  schedule:
    - cron: '15 22 * * *'
  push:
    branches:
      - main
    paths:
      - .signer/**/*.json

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["${{ github.event.inputs.python-version || '3.10' }}"]

    env: # 设置全局环境变量
      TZ: Asia/Shanghai # 设置为东八区时间

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-pip-deps-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ matrix.python-version }}-pip-deps-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -U tg-signer TgCrypto
        env:
          PIP_CACHE_DIR: ~/.cache/pip

      - name: Check tg-signer install path
        run: |
          which tg-signer
          echo "tg-signer path is: $(which tg-signer)"

      - name: Show pip freeze
        run: |
          pip freeze

      - name: Run tg-signer
        run: |
          rm -rf ./tg-signer.log
          set -e
          $(which tg-signer) run-once

      - name: Rename log to md
        run: |
          mkdir -p $(dirname ./$(date +%Y/%m/%d).md)
          mv ./tg-signer.log ./$(date +%Y/%m/%d).md
          cp ./$(date +%Y/%m/%d).md ./log.md
      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: translator
        run: npx ai-markdown-translator@1.0.15 -i log.md -l "中文，并重新整理为markdown格式（要求整理标题和内容，要很好的区分每个对应的任务和内容）"

      - name: Commit and push changes
        run: |
          git config --local user.email "action@h7ml.cn"
          git config --local user.name "GitHub Action"
          git config advice.ignoredHook false
          git add ./$(date +%Y/%m/%d).md ./log.md
          git add .signer
          git commit -m "check $(date +%Y/%m/%d)" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
