name: check

on:
  workflow_dispatch:
    inputs:
      python-version:
        type: string
        default: '3.10'
        description: 'Python version to use'
  schedule:
    - cron: '0 6 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -U tg-signer TgCrypto

      - name: Check tg-signer install path
        run: |
          which tg-signer
          echo "tg-signer path is: $(which tg-signer)"

      - name: Show pip freeze
        run: |
          pip freeze
      - name: echo tg-signer path
        run: |
          echo "tg-signer path is: $(which tg-signer)"
      - name: Run tg-signer
        run: |
          set -e
          $(which tg-signer) run-once
